# Generated by Django 4.1.5 on 2023-01-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_url', models.URLField(max_length=300)),
                ('prod_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_url', models.URLField(max_length=300)),
                ('prod_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_url', models.URLField(max_length=300)),
                ('prod_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product4',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_url', models.URLField(max_length=300)),
                ('prod_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
